version: '3.9'
services:
  # SQL Server Express container
  sql-server-express:
    # Use the SQL Server Docker image from Microsoft
    image: mcr.microsoft.com/mssql/server:latest
    # Add the container name
    container_name: docker-sql-server-express
    # Set environment variables for SQL Server configuration
    environment:
      - ACCEPT_EULA=Y # Accept the End-User License Agreement
      - SA_PASSWORD=MyPass@word # Set the 'sa' user password
      - MSSQL_PID=Express
    # Map host machine port 1433 to container port 1433 for SQL Server
    ports:
      - "1433:1433"