version: '3.9'
services:  
  mssql:    
    image: mcr.microsoft.com/mssql/server:2022-latest    
    container_name: mssql-db
    hostname: mssql-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin@1234
      - MSSQL_DATA_DIR=/var/opt/mssql/data
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT=1433 
    ports:
      - "1455:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets